M48
; DRILL file {KiCad (6.0.7)} date Sun Sep 25 19:14:50 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-25T19:14:50-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
%
G90
G05
T1
X4.7Y-2.5
X4.7Y-2.7
X4.7Y-2.9
X5.1Y-2.5
X5.1Y-2.7
X5.1Y-2.9
X5.25Y-2.525
X5.25Y-2.925
X5.6Y-2.475
X5.6Y-2.875
T0
M30
